name: re_ucm_workspace
description: ""
publish_to: none

environment:
  sdk: ^3.11.0

workspace:
  - re_ucm_*

dependency_overrides:
  flutter_inappwebview:
    git:
      url: https://github.com/pichillilorenzo/flutter_inappwebview.git
      path: flutter_inappwebview
