name: re_ucm_core
description: "ReUCM Core"
version: 1.8.0
homepage: "https://reucm.pages.dev"
publish_to: none
repository: https://github.com/BooksFine/re_ucm_core

environment:
  sdk: ^3.11.0

resolution: workspace

dependencies:
  logger: ^2.5.0

dev_dependencies:
  lints: ^6.0.0
