name: re_ucm_author_today
description: "Plugin that adds Author.Today support to ReUCM"
version: 1.2.0
homepage: "https://reucm.pages.dev"
repository: https://github.com/BooksFine/re_ucm_author_today
publish_to: none

environment:
  sdk: ^3.11.0

resolution: workspace

dependencies:
  crypto: ^3.0.6
  dio: ^5.7.0
  pointycastle: ^4.0.0
  re_ucm_core: any
  retrofit: ^4.4.1
  json_annotation: ^4.10.0
  freezed_annotation: ^3.1.0

dev_dependencies:
  build_runner: ^2.4.13
  lints: ^6.0.0
  retrofit_generator: ^10.2.1
  freezed: ^3.2.5
  json_serializable: ^6.13.0

flutter:
  assets:
    - assets/logo.svg
