name: re_ucm_author_today
description: "Plugin that adds Author.Today support to ReUCM"
version: 1.2.0
homepage: "https://reucm.pages.dev"
repository: https://github.com/BooksFine/re_ucm_author_today
publish_to: none

environment:
  sdk: ^3.11.0
  flutter: ^3.29.3

resolution: workspace

dependencies:
  crypto: ^3.0.6
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_inappwebview: any
  flutter_mobx: ^2.2.1+1
  flutter_svg: ^2.0.10+1
  json_annotation: ^4.9.0
  mobx: ^2.3.3+2
  path_provider: ^2.1.4
  pointycastle: ^4.0.0
  re_ucm_core: any
  retrofit: ^4.4.1
  sembast: ^3.7.5

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^6.0.0
  json_serializable: ^6.8.0
  mobx_codegen: ^2.6.1
  retrofit_generator: ^10.2.1

flutter:
  assets:
    - assets/logo.svg
