name: re_ucm
description: ""
publish_to: none
homepage: "https://reucm.pages.dev"
repository: "https://github.com/BooksFine/re_ucm"
version: 2.4.0+14321

environment:
  sdk: ^3.11.0
  flutter: ^3.29.3

resolution: workspace

dependencies:
  re_ucm_core: ^1.8.0
  re_ucm_author_today: ^1.2.0

  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  flutter_mobx: ^2.2.1+1
  go_router: ^17.1.0
  intl: ^0.20.2
  loading_animation_widget: ^1.2.1
  mobx: ^2.3.3+2
  path_provider: ^2.1.3
  sembast: ^3.7.1+2
  share_plus: ^12.0.1
  shimmer: ^3.0.0
  simple_html_css: ^5.0.0
  url_launcher: ^6.3.0

  xml: ^6.5.0
  flutter_inappwebview: any

  dio: ^5.6.0
  flutter_svg: ^2.0.10+1
  share_handler: ^0.0.21
  file_picker: ^10.1.9
  permission_handler: ^12.0.0+1
  ota_update_fork: ^6.0.0
  path: ^1.9.0
  html: ^0.15.6
  logger: ^2.5.0
  text_balancer: ^0.1.6
  dart_mappable: ^4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.9
  dart_mappable_builder: ^4.6.1
  mobx_codegen: ^2.7.1
  icons_launcher: ^3.0.0
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: lib/assets/fonts/RobotoFlex-VariableFont.ttf

  assets:
    - lib/assets/logo.webp
